let list = ["Talha", "Noman", "Saad"];
console.log("Hey " + list[0] + ", Lets have dinner this Sunday");
console.log("Hey " + list[1] + ", Lets have dinner this Sunday");
console.log("Hey " + list[2] + ", Lets have dinner this Sunday");
console.log("\nJust came to know that " + list[1] + " is not coming due to some issue");
console.log("\nIn his place now Waqar will join the dinner\n");
list.splice(1, 1, "Waqar");
console.log("Hey " + list[0] + ", Lets have dinner this Sunday");
console.log("Hey " + list[1] + ", Lets have dinner this Sunday");
console.log("Hey " + list[2] + ", Lets have dinner this Sunday");
console.log("\nI have got a bigger table now, so can invite more guests\n");
list.unshift("Kifayat");
list.push("Kamran");
list.splice(2, 0, "Khurram");
console.log("Hey " + list[0] + ", Lets have dinner this Sunday");
console.log("Hey " + list[1] + ", Lets have dinner this Sunday");
console.log("Hey " + list[2] + ", Lets have dinner this Sunday");
console.log("Hey " + list[3] + ", Lets have dinner this Sunday");
console.log("Hey " + list[4] + ", Lets have dinner this Sunday");
console.log("Hey " + list[5] + ", Lets have dinner this Sunday");
console.log("\nThe table have been delayed and as such, I can only invite 2 people\n");
console.log("Sorry " + list[2] + ", I can't invite you this time");
list.splice(2, 1);
console.log("Sorry " + list[2] + ", I can't invite you this time");
list.splice(2, 1);
console.log("Sorry " + list[0] + ", I can't invite you this time");
list.shift();
console.log("Sorry " + list[2] + ", I can't invite you this time");
list.pop();
console.log("Hey " + list[0] + ", Lets have dinner this Sunday");
console.log("Hey " + list[1] + ", Lets have dinner this Sunday");
list.splice(0, 2);
console.log(list);
export {};
